image:
  file: .gitpod/Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 10000
    onOpen: ignore
tasks:
   - name: "Live Preview"
     command: yarn install && yarn dev
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true
vscode:
  extensions:
    - svelte.svelte-vscode
    - voorjaar.windicss-intellisense
    - esbenp.prettier-vscode
